const questions = [
    { id: 'q1', text: 'What is 2+2?', 
        possible: [
            {id: 'a', text: '2'},
            {id: 'b', text: '4'},
            {id: 'c', text: '0'},
            {id: 'd', text: '1'}],
        answer: 'b' },
    { id: 'q2', text: 'What is 3x4?', 
        possible: [
            {id: 'a', text: '12'},
            {id: 'b', text: '16'},
            {id: 'c', text: '9'},
            {id: 'd', text: '7'}],
        answer: 'a' },
    { id: 'q3', text: 'What is 4/2?', 
        possible: [
            {id: 'a', text: '8'},
            {id: 'b', text: '2'},
            {id: 'c', text: '1'},
            {id: 'd', text: '0'}],
        answer: 'b'},
    { id: 'q4', text: 'What is 2^4?', 
        possible: [
            {id: 'a', text: '2'},
            {id: 'b', text: '8'},
            {id: 'c', text: '4'},
            {id: 'd', text: '16'}],
        answer: 'd' },
    { id: 'q5', text: 'What is 20x5', 
        possible: [
            {id: 'a', text: '25'},
            {id: 'b', text: '4'},
            {id: 'c', text: '15'},
            {id: 'd', text: '100'}],
        answer: 'd' },
    { id: 'q6', text: 'What is 2(3+4)', 
        possible: [
            {id: 'a', text: '9'},
            {id: 'b', text: '14'},
            {id: 'c', text: '1'},
            {id: 'd', text: '7'}],
        answer: 'b' },
    { id: 'q7', text: 'If this driver is driving at 45 miles per hour, how long would it take the driver to drive 15 miles?', 
        possible: [
            {id: 'a', text: '20 minutes'},
            {id: 'b', text: '45 minutes'},
            {id: 'c', text: '60 minutes'},
            {id: 'd', text: '15 minutes'}],
        answer: 'a' },
    { id: 'q8', text: 'Sally needs to pick 100 apples from her trees to sell to the market tomorrow. However, her basket can only carry 7 pounds. If each apple is .75 pounds, how many times would she need to fill up her basket?', 
        possible: [
            {id: 'a', text: '15 times'},
            {id: 'b', text: '10 times'},
            {id: 'c', text: '19 times'},
            {id: 'd', text: '20 times'}],
        answer: 'c' },
    { id: 'q9', text: 'What is 2x4x3x5?', 
        possible: [
            {id: 'a', text: '120'},
            {id: 'b', text: '14'},
            {id: 'c', text: '28'},
            {id: 'd', text: '2'}],
        answer: 'a' },
    { id: 'q10', text: 'John worked 62 hours this week while making $21 per hour. With overtime starting after 40 hours and his pay being increased by 1.5 times, how much did John make this week?', 
        possible: [
            {id: 'a', text: '$1218'},
            {id: 'b', text: '$1302'},
            {id: 'c', text: '$1533'},
            {id: 'd', text: '$1953'}],
        answer: 'c' },
    { id: 'q11', text: '', possible: '', answer: '' },
    { id: 'q12', text: '', possible: '', answer: '' },
    { id: 'q13', text: '', possible: '', answer: '' },
    { id: 'q14', text: '', possible: '', answer: '' },
    { id: 'q15', text: '', possible: '', answer: '' },
    { id: 'q16', text: '', possible: '', answer: '' },
    { id: 'q17', text: '', possible: '', answer: '' },
    { id: 'q18', text: '', possible: '', answer: '' },
    { id: 'q19', text: '', possible: '', answer: '' },
    { id: 'q20', text: '', possible: '', answer: '' },
]